INSERT INTO Employee ( FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('Cardinal','Tom B. Erichsen','IT','8000','2018-11-12','Norway');
INSERT INTO Employee ( FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('Nikita','Jain','IT','7000','2017-11-12','London');
INSERT INTO Employee ( FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('John','Deniel','HR','6000','2016-10-11','Delhi');
INSERT INTO Employee ( FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('Emly','DER','HR','8000','2018-11-12','Norway');