INSERT INTO Employee (ID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('1','Cardinal','Tom B. Erichsen','IT','8000','2018-11-12','Norway');
INSERT INTO Employee (ID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('2','Nikita','Jain','IT','7000','2017-11-12','London');
INSERT INTO Employee (ID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('3','John','Deniel','HR','6000','2016-10-11','Delhi');
INSERT INTO Employee (ID, FIRSTNAME, LASTNAME, DEPARTMENT, SALARY, STARTDATE, OFFICELOCATION)
VALUES ('4','Emly','DER','HR','8000','2018-11-12','Norway');