DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee(ID long PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), DEPARTMENT VARCHAR(255), SALARY NUMERIC(255), STARTDATE  DATE , OFFICELOCATION  VARCHAR(255));
DROP TABLE IF EXISTS LUCKYDRAW
CREATE TABLE LUCKYDRAW(LuckyDrawNumber long, LUCKYDRAWDATE DATE, ID long FOREIGN KEY REFERENCES Employee);