CREATE TABLE Employee(ID long PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), DEPARTMENT VARCHAR(255), SALARY NUMERIC(255), STARTDATE  DATE , OFFICELOCATION  VARCHAR(255));
CREATE TABLE LUCKYDRAW(LuckyDrawNumber long, LUCKYDRAWDATE DATE, WINNER_EMPID long);
ALTER TABLE LUCKYDRAW ADD FOREIGN KEY (WINNER_EMPID) REFERENCES Employee(ID);